config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  } 
  root "products#index"
  get 'search', to: 'products#search'

  resources :users, only: [:show, :edit, :update]
  resources :products do
    collection do
      get 'search', to: 'products#search'
      get 'category_children', defaults: { format: 'json'}
      get 'category_grandchildren', defaults: { format: 'json'}
    end
  end  
  resources :categories
  resources :cards, only: [:new, :show, :destroy] do
    collection do
      post 'pay_show', to: 'cards#pay_show'
      post 'pay', to: 'cards#pay'
    end
  end
  resources :transactions, only: [:index] do
    collection do
      get 'pay_index', to: 'transactions#pay_index'
      post 'pay', to: 'transactions#pay'
      get 'done', to: 'transactions#done'
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require "payjp"
  before_action :set_card, only: [:new, :show, :pay_show, :destroy]

  def new
    gon.payjp_key = ENV['PAYJP_KEY']
    if @set_card.exists?
      @card = @set_card.first
      redirect_to action: "show", id: @card.id
    end
  end

  def pay #payjpとCardのデータベース作成を実施
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト',
      email: current_user.email,
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) #metadataにuser_idを入れましたがなくてもOK
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "pay_show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def destroy #PayjpとCardデータベースを削除
    @card = @set_card.first
    if @card.present?
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
    end
      redirect_to action: "new"
  end

  def show #Cardのデータpayjpに送り情報を取り出す
    @card = @set_card.first
    if @card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  private

  def set_card
    @set_card = Card.where(user_id: current_user.id)
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/new.html.haml
.card-new
  .card-new__head
  .card-new__content
    .card-new__title
      クレジットカード情報入力
    .card-new__form
      = form_tag(pay_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
        .card-new__form-group--num
          .card-new__form-text
            .card-new__form-title
              %label カード番号
            .card-new__form-required
              必須
          = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
          .card-new__form-brand
            = image_tag "logo/card-brand-logo.png", class: 'card-new__form-brand--img', alt:"ロゴ"
        %br
        .card-new__form-group--deadline
          .card-new__form-text
            .card-new__form-title
              %label 有効期限
            .card-new__form-required
              必須
          %select#exp_month{name: "exp_month", type: "text"}
            %option{value: ""} --
            %option{value: "1"}01
            %option{value: "2"}02
            %option{value: "3"}03
            %option{value: "4"}04
            %option{value: "5"}05
            %option{value: "6"}06
            %option{value: "7"}07
            %option{value: "8"}08
            %option{value: "9"}09
            %option{value: "10"}10
            %option{value: "11"}11
            %option{value: "12"}12
          %span.card-new__form-deadline-day 月
          %select#exp_year{name: "exp_year", type: "text"}
            %option{value: ""} --
            %option{value: "2019"}19
            %option{value: "2020"}20
            %option{value: "2021"}21
            %option{value: "2022"}22
            %option{value: "2023"}23
            %option{value: "2024"}24
            %option{value: "2025"}25
            %option{value: "2026"}26
            %option{value: "2027"}27
            %option{value: "2028"}28
            %option{value: "2029"}29
          %span.card-new__form-deadline-day 年
        %br
        .card-new__form-group--cvc
          .card-new__form-text
            .card-new__form-title
              %label セキュリティコード
            .card-new__form-required
              必須
          = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
        #card_token
        .card-new__btn-box
          = submit_tag "追加する", id: "token_submit"
  .card-new__foot

app/views/cards/show.html.haml
.card-show
  .card-show__head
  .card-show__content
    .card-show__title
      支払い方法
    .card-show__main
      .card-show__main-title
        %label 登録クレジットカード情報
      .card-show__main-primary
        .card-show__card
          .card-show__card-num
            = "**** **** **** " + @default_card_information.last4
          .card-show__card-deadline
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
        .card-show__delete
          = form_tag(card_path, method: :delete, id: 'charge-form',  name: "inputForm") do
            %input{ type: "hidden", name: "card_id", value: "" }
            %button.card-show__delete-btn 削除する
      .card-show__main-bottom
  .card-show__foot