config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  } 
  root "products#index"
  get 'search', to: 'products#search'

  resources :users, only: [:show, :edit, :update]
  resources :products do
    collection do
      get 'search', to: 'products#search'
      get 'category_children', defaults: { format: 'json'}
      get 'category_grandchildren', defaults: { format: 'json'}
    end
  end  
  resources :categories
  resources :cards, only: [:new, :show, :destroy] do
    collection do
      post 'pay_show', to: 'cards#pay_show'
      post 'pay', to: 'cards#pay'
    end
  end
  resources :transactions, only: [:index] do
    collection do
      get 'pay_index', to: 'transactions#pay_index'
      post 'pay', to: 'transactions#pay'
      get 'done', to: 'transactions#done'
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_ancestry
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def index

  end
  
  def new
    @children = Category.where(ancestry: params[:parent_id])
    respond_to do |format|
      format.html
      format.json{render json: @children}
    end
  end

  def show
    @category = Category.find(params[:id])
    @category_products = Product.where(category_id: @category.id)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.haml
.category
  .category_list
    .category_list_title
      カテゴリー一覧
      %ul.category_name_list
        - @categories.each do |categories|
          %li.category_name
            =  link_to categories_path(categories) do
              %div #{categories.name}
    -# ここからカテゴリー別ゾーン
  - @categories.each do |categories|
    .category_list_box
      %ul.category_list_box_title
        %li #{categories.name}
      .category_list_box_individual
        %div
          = link_to categories_path(categories) do
            すべて
        - categories.children.each do |child|
          .category_list_box_individual_sub_category_name
            %h4
              = child.name
          .category_list_box_individual_sub_sub_category_box
            .category_list_box_individual_sub_sub_category_name
              - child.children.each do |grandchild|
                %div
                  = link_to categories_path(grandchild) do
                    = link_to grandchild.name, category_path(grandchild)

app/views/categories/show.html.haml
.top
  .top__genre
    .top__genre-box
      .top__genre-box-title
        = @category.name
        の商品一覧
    .top__genre-items
      - if @category_products.present?
        - @category_products.each do |product|
          .top__genre-item
            = link_to product_path(product.id), class:"top__genre-item-link" do
              .top__genre-item-pict
                = image_tag product.images.first.image.url, alt:"商品画像", class: "top__genre-item-img"
              .top__genre-body
                .top__genre-body-price
                  .top__genre-body-price--yen
                    ¥
                  .top__genre-body-price--value
                    = product.price
                .top__genre-body-name
                  = product.name
                -# 後ほど追加実装
                -# -# 商品購入済みであればSOLD OUTを表示
                -# - if @ladies_transaction.present?
                -#   - if @ladies_transaction.first.product_id == product.id
                -#     .top__transaction-check
                -#       .top__transaction-check--btn
                -#         SOLD OUT
      - else
        = @category.name
        の商品は現在ありません