config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  } 
  root "products#index"
  get 'search', to: 'products#search'

  resources :users, only: [:show, :edit, :update]
  resources :products do
    collection do
      get 'search', to: 'products#search'
      get 'category_children', defaults: { format: 'json'}
      get 'category_grandchildren', defaults: { format: 'json'}
    end
  end  
  resources :categories
  resources :cards, only: [:new, :show, :destroy] do
    collection do
      post 'pay_show', to: 'cards#pay_show'
      post 'pay', to: 'cards#pay'
    end
  end
  resources :transactions, only: [:index] do
    collection do
      get 'pay_index', to: 'transactions#pay_index'
      post 'pay', to: 'transactions#pay'
      get 'done', to: 'transactions#done'
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category, optional: true
  has_many :images, dependent: :destroy
  has_one :trade, class_name:"Transaction", dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  validates :name, presence: true, length: { maximum: 40 }
  validates :description, length: { maximum: 1000 }
  validates :images, :status, :delivery_charge, :delivery_method, :delivery_prefecture, :delivery_days, :size, :category, presence: true
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999}, presence: true

  enum delivery_charge:{
    "送料込み(出品者負担)": 1,
    "着払い(購入者負担)":2
  }
  enum delivery_method:{
    "未定": 1,
    "らくらくメルカリ便": 2,
    "ゆうメール": 3,
    "レターパック": 4,
    "普通郵便(定形、定形外)": 5,
    "クロネコヤマト": 6,
    "ゆうパック": 7,
    "クリックポスト": 8,
    "ゆうパケット": 9
  }
  enum delivery_prefecture:{
    "北海道":1,"青森県":2,"岩手県":3,"宮城県":4,"秋田県":5,"山形県":6,"福島県":7,
    "茨城県":8,"栃木県":9,"群馬県":10,"埼玉県":11,"千葉県":12,"東京都":13,"神奈川県":14,
    "新潟県":15,"富山県":16,"石川県":17,"福井県":18,"山梨県":19,"長野県":20,
    "岐阜県":21,"静岡県":22,"愛知県":23,"三重県":24,
    "滋賀県":25,"京都府":26,"大阪府":27,"兵庫県":28,"奈良県":29,"和歌山県":30,
    "鳥取県":31,"島根県":32,"岡山県":33,"広島県":34,"山口県":35,
    "徳島県":36,"香川県":37,"愛媛県":38,"高知県":39,
    "福岡県":40,"佐賀県":41,"長崎県":42,"熊本県":43,"大分県":44,"宮崎県":45,"鹿児島県":46, 
    "沖縄県":47
  }
  enum delivery_days:{
    "1~2日で発送": 1,
    "2~3日で発送": 2,
    "3~7日で発送": 3,
  }
  enum status:{
    "新品、未使用": 1,
    "未使用に近い": 2,
    "目立った傷や汚れなし": 3,
    "やや傷や汚れあり": 4,
    "傷や汚れあり": 5,
    "全体的に状態が悪い": 6
  }
  enum size:{
    "XXS以下": 1,
    "XS(SS)": 2,
    "S": 3,
    "M": 4,
    "L": 5,
    "XL(LL)": 6,
    "2XL(3L)": 7,
    "3XL(4L)": 8,
    "4XL(5L)以上": 9,
    "FREE SIZE":10
  }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except:[:index, :show]
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    # 検索機能
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true)
    @categories = Category.all.order("id ASC").limit(13)
    # カテゴリー別 一覧表示
    @ladies_products = Product.where(category_id: 20..85).limit(10)
    @mens_products = Product.where(category_id: 91..144).limit(10)
    @appliances_products = Product.where(category_id: 408..434).limit(10)
    # カテゴリー別 Sold Out Check
    @ladies_transaction = Transaction.where(product_id: @ladies_products.ids)
    @mens_transaction = Transaction.where(product_id: @mens_products.ids)
    @appliances_transaction = Transaction.where(product_id: @appliances_products.ids)
  end

  def search
    @q = Product.search(search_params)
    @search_products = @q.result(distinct: true)
    @categories = Category.order("id ASC").limit(13)
  end

  def new
    @product = Product.new
    @image = @product.images.build
    @category = Category.all.order("id ASC").limit(13)
    #セレクトボックスの初期値設定
    @category_parent_array = ["選択してください"]
    #データベースから、親カテゴリーのみ抽出し、配列化
    Category.where(ancestry: nil).each do |parent|
        @category_parent_array << parent.name
    end
  end

  def create
    @product = Product.new(product_params)
      if @product.save
        redirect_to product_path(@product.id)
      else
        @product.images.build
        redirect_to new_product_path
      end
  end

  def show
    @top_image = @product.images.first
    @images = @product.images
    # SOLD OUT確認用
    @transaction_check = Transaction.where(product_id: @product.id)
  end

  def edit
    @category = Category.order("id ASC").limit(13)
    @product = Product.find(params[:id]).presence || "商品は存在しません"

    # 親セレクトボックスの初期値(配列)
    @category_parent_array = []
    # categoriesテーブルから親カテゴリーのみを抽出、配列に格納
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end
    # itemに紐づいていいる孫カテゴリーの親である子カテゴリが属している子カテゴリーの一覧を配列で取得
    @category_child_array = @product.category.parent.parent.children
    # itemに紐づいていいる孫カテゴリーが属している孫カテゴリーの一覧を配列で取得
    @category_grandchild_array = @product.category.parent.children
  end

  def update
    @product = Product.find(params[:id])
      if @product.update(product_update_params)
        redirect_to product_path(@product.id)
      else
        redirect_to edit_product
      end
  end

  def category_children 
    @category_children = Category.find_by(name: "#{params[:name]}", ancestry: nil).children
  end

  def category_grandchildren
    @category_grandchildren = Category.find("#{params[:name]}").children
  end

  def destroy
    @product = current_user.products.find(params[:id])
    if @product.destroy
      redirect_to root_path
    else
      render 'show'
    end
  end

  private

  def product_params
    params.require(:product).permit(
      :name, :description, :status, :delivery_charge, :delivery_method, :delivery_prefecture, :delivery_days, :size, :brand, :price, :transaction_id, :category_id,
      [images_attributes: [:image]]).merge(user_id: current_user.id)
  end

  def product_update_params
    params.require(:product).permit(
      :name, :description, :status, :delivery_charge, :delivery_method, :delivery_prefecture, :delivery_days, :size, :brand, :price, :transaction_id, :category_id,
      [images_attributes: [:image, :_destroy, :id]]).merge(user_id: current_user.id)
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def set_user
    @user = User.find(@product.user_id)
  end

  def search_params
    params.require(:q).permit(:name_cont)
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_search_form.html.haml
= search_form_for(@q, url:search_path) do |f|
  .header__center__up__search
    .search
      = f.search_field :name_cont, class: "form", placeholder: "何かお探しですか？"
      %button.searchForm-submit{:type => "submit"}

app/views/products/edit.html.haml
.exhibition
  = form_with model: @product, local: true do |f|
    .exhibition__logo__box
      = link_to image_tag("logo/logo.png", class: "exhibition__logo", alt: "furima"),root_path, class: "exhibition__logo"
    %main
      .exhibition__container__header
        商品の情報を入力
      .upload__box.exhibition__content__box
        .sell__block__form__upload
          %h3.sell__block__form__upload__head
            出品画像
            %span.form-description.form-require 必須
            %p 最大5枚までアップロードできます
          .post__drop__box__container
            .prev-content
              //JSで挿入したhtmlと同じ形　each文でのプレビュー表示
              - @product.images.each do |image|
                .preview-box
                  .upper-box
                    = image_tag image.image.url, width: "112", height: "112", alt: "preview"
                  .lower-box
                    .delete-box
                      .delete-btn
                        %span 削除
            .label-content
              //プレビューの数に合わせてforオプションを指定
              = f.label :"images_attributes_#{@product.images.length}_image", class: "label-box", id: "label-box--#{@product.images.length}" do
                %pre.label-box__text-visible クリックしてファイルをアップロード
            .hidden-content
              = f.fields_for :images do |i|
                //プレビューが出ている分のfile_fieldとdelete用のチェックボックスを設置
                = i.file_field :image, class: "hidden-field"
                = i.check_box:_destroy, class: "hidden-checkbox"
                //5つのfile_fieldを準備するに当たって、足りない分を表示
              - @product.images.length.upto(4) do |i|
                %input{name: "product[images_attributes][#{i}][image]", id: "product_images_attributes_#{i}_image", class:"hidden-field", type:"file"}

      .exhibition__content__box.product__box
        .form__group1
          = f.label :name do
            商品名
            %span.form-description.form-require 必須
          = f.text_field :name, {placeholder: "商品名（必須 40文字まで)", class: "name__input", maxlength: '40'}
        .form__group1
          = f.label :description do
            商品の説明
            %span.form-description.form-optional 任意
          = f.text_area :description, {placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", class: "description__input", maxlength: '1000'}  
      .exhibition__content__box.detail__box
        .section__head
          商品の詳細
        .form__box.detail__form__box
          .form__box__above

            .form-group-top
              .form__group2
                = f.label :カテゴリー, class: "label" do
                  カテゴリー
                  %span.form-description.form-require 必須
                %br
                = f.select :category_id, options_for_select(@category_parent_array.map{|c|[c, {}]}, @product.category.parent.parent.name), {}, {class: 'exhibition__select', id: 'parent_category'}
              .form__group2#children_box
                = f.select :category_id, options_for_select(@category_child_array.map{|c|[c[:name], c[:id], {'data-category'=>c[:id], 'id'=>c[:id]}]}, @product.category.parent.id), {}, {class: 'exhibition__select', id: 'children_category'}
              .form__group2#grandchildren_box
                = f.select :category_id, options_for_select(@category_grandchild_array.map{|c|[c[:name], c[:id], {'data-category'=>c[:id], 'id'=>c[:id]}]}, @product.category.id), {}, {class: 'exhibition__select', id: 'grandchildren_category'}
              = f.text_field :category, id: 'grand_child_result_id', type: 'hidden'

          .form__box__bellow
            .form__group2
              = f.label :size do
                サイズ
                %span.form-description.form-require 必須
              = f.select :size, Product.sizes.keys,{include_blank: '選択してください'},{class: "exhibition__select"}
            .form__group2
              = f.label :brand do
                ブランド
                %span.form-description.form-optional 任意
              = f.text_field :brand, {placeholder: "例) シャネル", class: "brand__input exhibition__select"}
            .form__group2
              = f.label :status do
                商品の状態
                %span.form-description.form-require 必須
              = f.select :status, Product.statuses.keys,{include_blank: '選択してください'},{class: "exhibition__select"}
      -# 配送
      .exhibition__content__box.shipping__box
        .section__head
          配送について
          = link_to "" do
            = icon('fas', 'question-circle', class: "question__icon") 
        .form__box
          .form__group3
            = f.label :delivery_charge do
              配送料の負担
              %span.form-description.form-require 必須
            = f.select :delivery_charge, Product.delivery_charges.keys,{include_blank: '選択してください'},{class: "exhibition__select"}
          .form__group3
            = f.label :delivery_method do
              配送の方法
              %span.form-description.form-require 必須
            = f.select :delivery_method, Product.delivery_methods.keys,{include_blank: '選択してください'},{class: "exhibition__select"}
          .form__group3
            = f.label :delivery_prefecture do
              発送元の地域
              %span.form-description.form-require 必須
            = f.select :delivery_prefecture, Product.delivery_prefectures.keys,{include_blank: '選択してください'},{class: "exhibition__select"}
          .form__group3
            = f.label :delivery_days do
              発送までの日数
              %span.form-description.form-require 必須
            = f.select :delivery_days, Product.delivery_days.keys,{include_blank: '選択してください'},{class: "exhibition__select"}
      .exhibition__content__box.price__box
        .section__head
          販売価格(300〜9,999,999)
          = link_to "" do
            = icon('fas', 'question-circle', class: "question__icon")  
        .form__box
          .from__group4.price__form
            %label.price 
              価格
              %span.form-description.form-require 必須
            .price__form__right
              %p.yen ¥
              = f.number_field :price, {placeholder: "例)300", class: "price__input", id: "price__num", oninput: "calcProfit();", min: 300, max: 9999999}
          .from__group4.commission__form
            .commission__form__left
              販売手数料(10%)
            .commission__form__right#commission__num
              ¥ #{(@product.price*0.1).to_i}
          .from__group4.profit__form
            .profit__form__left
              販売利益
            .profit__form__right#profit__num
              ¥ #{(@product.price*0.9).to_i}
      .exhibition__btn__box
        = link_to '禁止されている出品',''
        、
        = link_to '行為',''
        を必ずご確認ください。
        %p
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        = link_to '偽ブランドの販売',''
        は犯罪であり処罰される可能性があります。
        %p
        また、出品をもちまして
        = link_to '加盟店規約',''
        に同意したことになります。
        .exhibition__area
          = f.submit '変更する', class: 'exhibition__btn determine__btn', id: 'send'
        .return__area
          = link_to "戻る", root_path, class: 'return__btn determine__btn'

app/views/products/index.html.haml
.top
  .top__visual
    .top__visual-image-area
      = image_tag "pict/bg-mainVisual-pict_pc.jpg", class: "top__visual-image"
    .top__visual-content
      .top__visual-content--subtitle
        人生を変えるフリマアプリ
      .top__visual-content--text
        FURIMAはだれでもかんたんに出品・購入できる
        %br
        フリマアプリです
  .top__category
    .top__category-box
      .top__category-popular
        人気のカテゴリー
      .top__category-items
        %ul.top__category-lists
          %li.top__category-item
            レディース
          %li.top__category-item
            メンズ
          %li.top__category-item
            家電・スマホ・カメラ
          %li.top__category-item
            おもちゃ・ホビー・グッズ
  .top__genre
    .top__genre-box
      .top__genre-box-title
        レディース新着アイテム
    .top__genre-items
      -if @ladies_products.present?
        - @ladies_products.each do |product|
          .top__genre-item
            = link_to product_path(product.id), class:"top__genre-item-link" do
              .top__genre-item-pict
                = image_tag product.images.first.image.url, alt:"商品画像", class: "top__genre-item-img"
              .top__genre-body
                .top__genre-body-price
                  .top__genre-body-price--yen
                    ¥
                  .top__genre-body-price--value
                    = product.price
                .top__genre-body-name
                  = product.name
                -# 商品購入済みであればSOLD OUTを表示
                - if @ladies_transaction.present?
                  - if @ladies_transaction.first.product_id == product.id
                    .top__transaction-check
                      .top__transaction-check--btn
                        SOLD OUT
  .top__genre
    .top__genre-box
      .top__genre-box-title
        メンズ新着アイテム
    .top__genre-items
      -if @mens_products.present?
        - @mens_products.each do |product|
          .top__genre-item
            = link_to product_path(product.id), class:"top__genre-item-link" do
              .top__genre-item-pict
                = image_tag product.images.first.image.url, alt:"商品画像", class: "top__genre-item-img"
              .top__genre-body
                .top__genre-body-price
                  .top__genre-body-price--yen
                    ¥
                  .top__genre-body-price--value
                    = product.price
                .top__genre-body-name
                  = product.name
                -# 商品購入済みであればSOLD OUTを表示
                - if @mens_transaction.present?
                  - if @mens_transaction.first.product_id == product.id
                    .top__transaction-check
                      .top__transaction-check--btn
                        SOLD OUT
  .top__genre
    .top__genre-box
      .top__genre-box-title
        家電・スマホ・カメラ新着アイテム
    .top__genre-items
      -if @appliances_products.present?
        - @appliances_products.each do |product|
          .top__genre-item
            = link_to product_path(product.id), class:"top__genre-item-link" do
              .top__genre-item-pict
                = image_tag product.images.first.image.url, alt:"商品画像", class: "top__genre-item-img"
              .top__genre-body
                .top__genre-body-price
                  .top__genre-body-price--yen
                    ¥
                  .top__genre-body-price--value
                    = product.price
                .top__genre-body-name
                  = product.name
                -# 商品購入済みであればSOLD OUTを表示
                - if @appliances_transaction.present?
                  - if @appliances_transaction.first.product_id == product.id
                    .top__transaction-check
                      .top__transaction-check--btn
                        SOLD OUT
.footer_sell
  = link_to new_product_path , class:"footer_sell_btn_link" do
    .footer_sell_btn
      .footer_sell_btn_word
        出品
      .footer_icon
        = icon('fas fa-camera', class: "camera_icon")

app/views/products/new.html.haml
.exhibition
  = form_with(model: @product, local: true) do |f|
    .exhibition__logo__box
      = link_to image_tag("logo/logo.png", class: "exhibition__logo", alt: "furima"),root_path, class: "exhibition__logo"
    %main
      .exhibition__container__header
        商品の情報を入力
      .upload__box.exhibition__content__box
        .upload__box__head
          出品画像
          %span.form-description.form-require 必須
        %p 最大5枚までアップロードできます
        .post__drop__box__container
          .prev-content
          .label-content
            %label{for: "product_images_attributes_0_image", class: "label-box", id: "label-box--0"}
              %pre.label-box__text-visible クリックしてファイルをアップロード
          .hidden-content
            = f.fields_for :images ,multiple: true do |i|
              = i.file_field :image, class: "hidden-field"
              %input{class:"hidden-field", type: "file", name: "product[images_attributes][1][image]", id: "product_images_attributes_1_image" }
              %input{class:"hidden-field", type: "file", name: "product[images_attributes][2][image]", id: "product_images_attributes_2_image" }
              %input{class:"hidden-field", type: "file", name: "product[images_attributes][3][image]", id: "product_images_attributes_3_image" }
              %input{class:"hidden-field", type: "file", name: "product[images_attributes][4][image]", id: "product_images_attributes_4_image" }
      .exhibition__content__box.product__box
        .form__group1
          = f.label :name do
            商品名
            %span.form-description.form-require 必須
          = f.text_field :name, {placeholder: "商品名（必須 40文字まで)", class: "name__input", maxlength: '40'}
        .form__group1
          = f.label :description do
            商品の説明
            %span.form-description.form-optional 任意
          = f.text_area :description, {placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", class: "description__input", maxlength: '1000'}  
      .exhibition__content__box.detail__box
        .section__head
          商品の詳細
        .form__box.detail__form__box
          .form__box__above
            .form__group2
              .form__label
                = f.label :category do
                  カテゴリー
                  %span.form-description.form-require 必須
              .form__select
                = f.select :category, @category_parent_array, {}, {class: "exhibition__select",id: "parent_category"}

          .form__box__bellow
            .form__group2
              = f.label :size do
                サイズ
                %span.form-description.form-require 必須
              = f.select :size, Product.sizes.keys,{include_blank: '選択してください'},{class: "exhibition__select"}
            .form__group2
              = f.label :brand do
                ブランド
                %span.form-description.form-optional 任意
              = f.text_field :brand, {placeholder: "例) シャネル", class: "brand__input exhibition__select"}
            .form__group2
              = f.label :status do
                商品の状態
                %span.form-description.form-require 必須
              = f.select :status, Product.statuses.keys,{include_blank: '選択してください'},{class: "exhibition__select"}
      -# 配送
      .exhibition__content__box.shipping__box
        .section__head
          配送について
          = link_to "" do
            = icon('fas', 'question-circle', class: "question__icon") 
        .form__box
          .form__group3
            = f.label :delivery_charge do
              配送料の負担
              %span.form-description.form-require 必須
            = f.select :delivery_charge, Product.delivery_charges.keys,{include_blank: '選択してください'},{class: "exhibition__select"}
          .form__group3
            = f.label :delivery_method do
              配送の方法
              %span.form-description.form-require 必須
            = f.select :delivery_method, Product.delivery_methods.keys,{include_blank: '選択してください'},{class: "exhibition__select"}
          .form__group3
            = f.label :delivery_prefecture do
              発送元の地域
              %span.form-description.form-require 必須
            = f.select :delivery_prefecture, Product.delivery_prefectures.keys,{include_blank: '選択してください'},{class: "exhibition__select"}
          .form__group3
            = f.label :delivery_days do
              発送までの日数
              %span.form-description.form-require 必須
            = f.select :delivery_days, Product.delivery_days.keys,{include_blank: '選択してください'},{class: "exhibition__select"}
      .exhibition__content__box.price__box
        .section__head
          販売価格(300〜9,999,999)
          = link_to "" do
            = icon('fas', 'question-circle', class: "question__icon")  
        .form__box
          .from__group4.price__form
            %label.price 
              価格
              %span.form-description.form-require 必須
            .price__form__right
              %p.yen ¥
              = f.number_field :price, {placeholder: "例)300", class: "price__input", id: "price__num", oninput: "calcProfit();", min: 300, max: 9999999}
          .from__group4.commission__form
            .commission__form__left
              販売手数料(10%)
            .commission__form__right#commission__num
              ¥ 
          .from__group4.profit__form
            .profit__form__left
              販売利益
            .profit__form__right#profit__num
              ¥
      .exhibition__btn__box
        = link_to '禁止されている出品',''
        、
        = link_to '行為',''
        を必ずご確認ください。
        %p
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        = link_to '偽ブランドの販売',''
        は犯罪であり処罰される可能性があります。
        %p
        また、出品をもちまして
        = link_to '加盟店規約',''
        に同意したことになります。
        .exhibition__area
          = f.submit '出品する', class: 'exhibition__btn determine__btn', id: 'send'
        .return__area
          = link_to "戻る", root_path, class: 'return__btn determine__btn'

app/views/products/search.html.haml
.top
  .top__genre
    .top__genre-box
      .top__genre-box-title
        = @q.name_cont
        の検索結果
    .top__genre-items
      - @search_products.each do |product|
        .top__genre-item
          = link_to product_path(product.id), class:"top__genre-item-link" do
            .top__genre-item-pict
              = image_tag product.images.first.image.url, alt:"商品画像", class: "top__genre-item-img"
            .top__genre-body
              .top__genre-body-price
                .top__genre-body-price--yen
                  ¥
                .top__genre-body-price--value
                  = product.price
              .top__genre-body-name
                = product.name
              -# 後ほど追加実装
              -# -# 商品購入済みであればSOLD OUTを表示
              -# - if @ladies_transaction.present?
              -#   - if @ladies_transaction.first.product_id == product.id
              -#     .top__transaction-check
              -#       .top__transaction-check--btn
              -#         SOLD OUT

app/views/products/show.html.haml
%script{src: "product/new.js", type: "text/javascript"}
.product-show
  .product-show__main
    .product-show__content
      .product-show__top-content
        .product-show__item-box
          .product-show__item-box--name
            = @product.name
          .product-show__item-box__body
            .product-show__item-box__body--top-img
              = image_tag @top_image.image.url, alt:"トップ画像", class: "product-show__item-top-img"
            .product-show__item-box__body--list
              - @images.each do |image|
                .product-show__item-box__body--sub-img
                  = image_tag image.image.url, alt:"サブ画像", class: "product-show__item-sub-img"
          .product-show__item-box--price
            %span 
            = "#{@product.price}円"
            .product-show__item-box--price-detail
              %span.product-show__item-box--price-detail-text
                (税込)
              %span.product-show__item-box--price-detail-text
                = @product.delivery_charge
          .product-show__item-box--item-detail
            = @product.name
          -# 商品出品者であれば表示させない
          - if user_signed_in? && (current_user.id == @product.user_id)
          - else
            .product-show__transaction
              .product-show__transaction-box
                -# 商品購入済みであれば購入させない
                - if @transaction_check.present?
                  .product-transaction-btn
                    SOLD OUT
                - else
                  = link_to "購入画面に進む", pay_index_transactions_path(product_id: @product), class: "product-transaction-btn"
          %table.product-show__item-box--table
            %tbody.product-show__item-box--table-body
              %tr.product-show__item-box--table-list
                %th.product-show__item-box--table-title
                  出品者
                %td.product-show__item-box--table-data
                  = @user.nickname
              %tr.product-show__item-box--table-list
                %th.product-show__item-box--table-title
                  カテゴリー
                %td.product-show__item-box--table-data
                  = link_to "#{@product.category.root.name}", "#", class: "product-show__table-link"
                  %br
                  = link_to "#{@product.category.parent.name}", "#", class: "product-show__table-link"
                  %br
                  = link_to "#{@product.category.name}", "#", class: "product-show__table-link"
              %tr.product-show__item-box--table-list
                %th.product-show__item-box--table-title
                  ブランド
                %td.product-show__item-box--table-data
                  = link_to "#{@product.brand}", "#", class: "product-show__table-link"
              %tr.product-show__item-box--table-list
                %th.product-show__item-box--table-title
                  商品のサイズ
                %td.product-show__item-box--table-data
                  = @product.size
              %tr.product-show__item-box--table-list
                %th.product-show__item-box--table-title
                  商品の状態
                %td.product-show__item-box--table-data
                  = @product.status
              %tr.product-show__item-box--table-list
                %th.product-show__item-box--table-title
                  配送料の負担
                %td.product-show__item-box--table-data
                  = @product.delivery_charge
              %tr.product-show__item-box--table-list
                %th.product-show__item-box--table-title
                  配送の方法
                %td.product-show__item-box--table-data
                  = @product.delivery_method
              %tr.product-show__item-box--table-list
                %th.product-show__item-box--table-title
                  発送元の地域
                %td.product-show__item-box--table-data
                  = link_to "#{@product.delivery_prefecture}", "#", class: "product-show__prefecture-link"
              %tr.product-show__item-box--table-list
                %th.product-show__item-box--table-title
                  発送日の目安
                %td.product-show__item-box--table-data
                  = @product.delivery_days
          .product-show__item-box--description
            = @product.description
        - if user_signed_in? && (current_user.id == @product.user_id)
          .seler-dedicated
            .edit-box
              = link_to '商品の編集', edit_product_path, method: :get, class: "determine_btn"
            .delete-box
              = link_to 'この商品を削除する', product_path(@product), method: :delete, class: "determine_btn", data: {confirm: "本当に削除しますか？"}
          -# 実装保留
          -# %ul.product-show__links
          -#   %li.product-show__links-list
          -#     = link_to "< 前の商品", "#", class: "product-show__links-link"
          -#   %li.product-show__links-list
          -#     = link_to "次の商品 >", "#", class: "product-show__links-link"
          -# .product-show__back-link
          -#   .product-show__back--text
          -#     = link_to "レディースをもっと見る", "#", class: "product-show__back-link"
.footer_sell
  = link_to new_product_path , class:"footer_sell_btn_link" do
    .footer_sell_btn
      .footer_sell_btn_word
        出品
      .footer_icon
        = icon('fas fa-camera', class: "camera_icon")