config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  } 
  root "products#index"
  get 'search', to: 'products#search'

  resources :users, only: [:show, :edit, :update]
  resources :products do
    collection do
      get 'search', to: 'products#search'
      get 'category_children', defaults: { format: 'json'}
      get 'category_grandchildren', defaults: { format: 'json'}
    end
  end  
  resources :categories
  resources :cards, only: [:new, :show, :destroy] do
    collection do
      post 'pay_show', to: 'cards#pay_show'
      post 'pay', to: 'cards#pay'
    end
  end
  resources :transactions, only: [:index] do
    collection do
      get 'pay_index', to: 'transactions#pay_index'
      post 'pay', to: 'transactions#pay'
      get 'done', to: 'transactions#done'
    end
  end
end

app/views/layouts/_brand.html.haml
%ul.header_brand{id:"item"}
  %li.header_brand_list
    %h3
      =  link_to categories_path("#") do
        シャネル
  %li.header_brand_list
    %h3
      =  link_to categories_path("#") do
        ナイキ
  %li.header_brand_list
    %h3
      =  link_to categories_path("#") do
        ルイ ヴィトン
  %li.header_brand_list
    %h3
      =  link_to categories_path("#") do
        シュプリーム
  %li.header_brand_list
    %h3
      =  link_to categories_path("#") do
        アディダス
  %li.header_brand_list
    %h3
      =  link_to categories_path("#") do
        ブランド一覧

app/views/layouts/_categories.html.haml
.categories-header-nav-parent-wrap{id:"header-categories"}
  .categories-header_main-categories
    - @categories.each do |categories|
      %div.parent_list
        =  link_to categories_path(categories),id:"#{categories.id}" do
          #{categories.name}
  .categories-header_sub-categories
    %div.children_list
  .categories-header_sub-sub-categories
    %div.Grandchild

app/views/layouts/_footer.html.haml
%footer
  .footer__nav
    .footer__nav__box
      %h2
        フリマについて
      %ul.footer__nav__box__lists
        %li.footer__nav__box__lists__list
          = link_to "会社概要（運営会社）", "#", class: "footer__nav__box__lists__list__link"
        %li.footer__nav__box__lists__list
          = link_to "採用情報", "#", class: "footer__nav__box__lists__list__link"
        %li.footer__nav__box__lists__list
          = link_to "プレスリリース", "#", class: "footer__nav__box__lists__list__link"
        %li.footer__nav__box__lists__list
          = link_to "公式ブログ", "#", class: "footer__nav__box__lists__list__link"
        %li.footer__nav__box__lists__list
          = link_to "フリマロゴ利用ガイドライン", "#", class: "footer__nav__box__lists__list__link"
      .footer__nav__box__sns
        = link_to "#" , class:"footer__nav__box__sns__link" do
          %svg{width: "29", height: "23" ,viewBox: "0 0 21 16" ,class: "footer__nav__box__sns__twitter"}
            %path{fill: "currentColor" ,d: "M6.343 15.969c7.61 0 11.773-6.134 11.773-11.444 0-.172 0-.345-.008-.517a8.303 8.303 0 0 0 2.066-2.086 8.576 8.576 0 0 1-2.38.635A4.07 4.07 0 0 0 19.616.329a8.377 8.377 0 0 1-2.63.973 4.186 4.186 0 0 0-3.019-1.27c-2.283 0-4.14 1.803-4.14 4.023 0 .314.041.62.106.918A11.866 11.866 0 0 1 1.404.769a3.936 3.936 0 0 0-.557 2.023c0 1.396.735 2.628 1.84 3.35a4.278 4.278 0 0 1-1.872-.503v.055c0 1.945 1.428 3.577 3.317 3.945-.347.094-.71.141-1.09.141-.266 0-.524-.023-.774-.07.524 1.6 2.057 2.76 3.865 2.792a8.452 8.452 0 0 1-5.14 1.725 8.19 8.19 0 0 1-.985-.054 12.02 12.02 0 0 0 6.335 1.796"}
        = link_to "#" , class:"footer__nav__box__sns__link" do
          %svg{width: "26" ,height: "26", viewBox: "0 0 16 16" ,class: "footer__nav__box__sns__facebook"}
            %path{fill: "currentColor" ,d: "M15.111 0H.89A.889.889 0 0 0 0 .889V15.11c0 .491.398.889.889.889h7.658V9.813H6.469V7.391h2.078V5.613c0-2.066 1.262-3.193 3.11-3.193.623-.002 1.244.03 1.863.096v2.15h-1.276c-1.002 0-1.197.478-1.197 1.178v1.543h2.397l-.31 2.422h-2.087V16h4.064c.491 0 .889-.398.889-.889V.89A.889.889 0 0 0 15.111 0z"}
    .footer__nav__box
      %h2
        ヘルプ＆ガイド
        %ul.footer__nav__box__lists
          %li.footer__nav__box__lists__list
            = link_to "フリマガイド", "#", class:"footer__nav__box__lists__list__link"
          %li.footer__nav__box__lists__list
            = link_to "らくらくフリマ便", "#", class:"footer__nav__box__lists__list__link"
          %li.footer__nav__box__lists__list
            = link_to "ゆうゆうフリマ便", "#", class:"footer__nav__box__lists__list__link"
          %li.footer__nav__box__lists__list
            = link_to "大型フリマ便", "#", class:"footer__nav__box__lists__list__link"
          %li.footer__nav__box__lists__list
            = link_to "車体取引ガイド", "#", class:"footer__nav__box__lists__list__link"
          %li.footer__nav__box__lists__list
            = link_to "フリマあんしん・あんぜん宣言！", "#", class:"footer__nav__box__lists__list__link"
          %li.footer__nav__box__lists__list
            = link_to "偽ブランド品撲滅への取り組み", "#", class:"footer__nav__box__lists__list__link"
          %li.footer__nav__box__lists__list
            = link_to "フリマボックス", "#", class:"footer__nav__box__lists__list__link"
          %li.footer__nav__box__lists__list
            = link_to "スマホ出品・売却相場", "#", class:"footer__nav__box__lists__list__link"
    .footer__nav__privacy
      %h2
        プライバシーと利用規約
        .footer__nav__privacy__box
          %ul.footer__nav__privacy__box__lists
            %li.footer__nav__privacy__box__lists__list
              = link_to "プライバシーポリシー", "#", class:"footer__nav__privacy__box__lists__list__link"
            %li.footer__nav__privacy__box__lists__list
              = link_to "フリマ利用規約", "#", class:"footer__nav__privacy__box__lists__list__link"
            %li.footer__nav__privacy__box__lists__list
              = link_to "あんしんスマホサポート制度に関する利用特約", "#", class:"footer__nav__privacy__box__lists__list__link"
            %li.footer__nav__privacy__box__lists__list
              = link_to "コンプライアンスポリシー", "#", class:"footer__nav__privacy__box__lists__list__link"
          %ul.footer__nav__privacy__box__lists
            %li.footer__nav__privacy__box__lists__list
              = link_to "個人データの安全管理に係る基本方針", "#", class:"footer__nav__privacy__box__lists__list__link"
            %li.footer__nav__privacy__box__lists__list
              = link_to "特定商取引に関する表記", "#", class:"footer__nav__privacy__box__lists__list__link"
            %li.footer__nav__privacy__box__lists__list
              = link_to "資金決済法に基づく表示", "#", class:"footer__nav__privacy__box__lists__list__link"
            %li.footer__nav__privacy__box__lists__list
              = link_to "法令順守と犯罪抑止のために", "#", class:"footer__nav__privacy__box__lists__list__link"
    .footer__nav__box
      %h2
        国
        %ul.footer__nav__box__lists
          %li.footer__nav__box__lists__list
            = link_to "日本", "#", class:"footer__nav__box__lists__list__link"
          %li.footer__nav__box__lists__list
            = link_to "United States", "#", class:"footer__nav__box__lists__list__link"
  .footer__bottom
    = link_to "#" , class:"footer__bottom__top_page" do
      = image_tag "logo/logo-white.png", alt: "Furima" ,class: "footer__bottom__top_page__logo"
    %span.footer__bottom__lisence
      = "© Furima, Inc."

app/views/layouts/_header.html.haml
%header
  .header__center
    .header__center__up
      = link_to image_tag("logo/logo.png", height: "50px", width: "175px", class: "header__center__up__mercari_logo"), root_path
      = render partial: 'products/search_form'
    .header__center__down
      .header__center__down__menu
        .header__center__down__menu__category
          %svg{width: "20" ,height: "44" ,viewBox: "0 0 20 16" ,class: "header__center__down__menu__category__icon"}
            %path{fill: "currentColor" , d: "M18.799 15.25h-11.5a1.25 1.25 0 1 1 0-2.5h11.5a1.25 1.25 0 0 1 0 2.5zm0-6h-11.5a1.25 1.25 0 1 1 0-2.5h11.5a1.25 1.25 0 0 1 0 2.5zm0-6h-11.5a1.25 1.25 0 1 1 0-2.5h11.5a1.25 1.25 0 0 1 0 2.5zM2 16a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm0-6a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm0-6a2 2 0 1 0 0-4 2 2 0 0 0 0 4z"}
          = link_to categories_path id:"header-category-link" do
            = "カテゴリーから探す"
            = render partial:"layouts/categories"
        -# .header__center__down__menu__brand
        -#   %svg{width: "23", height: "44" ,viewBox: "0 0 23 16" ,class: "header__center__down__menu__brand__icon"}
        -#     %path{fill: "currentColor" ,d: "M6.315 0L4.473 1.806 2.833.019.73 1.977l1.69 1.84L1.198 5.02c-1.594 1.594-1.594 4.188-.01 5.772L6.3 16h13.272a3.08 3.08 0 0 0 3.077-3.077V3.076A3.08 3.08 0 0 0 19.57 0H6.315zm13.46 12.925a.211.211 0 0 1-.205.205H7.504L3.227 8.771a1.226 1.226 0 0 1-.01-1.71L4.38 5.92l1.28 1.371a2.68 2.68 0 1 0 2.13-1.93L6.433 3.907 7.49 2.87h12.082a.211.211 0 0 1 .206.205v9.848h-.002z"}
        -#   = "ブランドから探す"
          = render partial:"layouts/brand"
      %ul.header__center__down__user_menu
        %li.header__center__down__user_menu__likes{style: "list-style:none"}
          %svg{width: "18", height: "44" ,viewBox: "0 0 16 15", class: "header__center__down__user_menu__likes__icon"}
            %path{fill: "currentColor" ,d: "M8.08 12.711l-.08.082-.08-.082C4.112 9.188 1.6 6.858 1.6 4.496c0-1.635 1.2-2.861 2.8-2.861 1.232 0 2.432.81 2.856 1.929h1.496c.416-1.12 1.616-1.93 2.848-1.93 1.6 0 2.8 1.227 2.8 2.862 0 2.362-2.512 4.692-6.32 8.215M11.6 0C10.208 0 8.872.662 8 1.708 7.128.662 5.792 0 4.4 0 1.936 0 0 1.978 0 4.496c0 3.09 2.72 5.608 6.84 9.433L8 15l1.16-1.079C13.28 10.104 16 7.586 16 4.496 16 1.978 14.064 0 11.6 0" }
            %h1.header__center__down__user_menu__likes__word
              = "いいね！一覧"
        %li.header__center__down__user_menu__notify{style: "list-style:none"}
          %svg{width: "18" ,height: "44" ,viewBox: "0 0 14 16", class: "header__center__down__user_menu__notify__icon"}
            %path{fill: "currentColor" ,d: "M6.592 16c.89 0 1.632-.734 1.632-1.632H4.928c0 .898.742 1.632 1.664 1.632zm4.896-4.928V6.976c-.008-2.521-1.345-4.63-3.712-5.184v-.576C7.79.55 7.241 0 6.56 0c-.68 0-1.23.55-1.216 1.216v.576c-2.36.554-3.704 2.654-3.712 5.184v4.096L0 12.704v.832h13.12v-.832l-1.632-1.632zm-1.632.832h-6.56V6.976c0-2.024 1.238-3.68 3.296-3.68 2.026 0 3.264 1.656 3.264 3.68v4.928z"}
          %h1.header__center__down__user_menu__norify__word
            = "お知らせ"
        %li.header__center__down__user_menu__todo{style: "list-style:none"}
          %svg{width: "18" ,height: "44" ,viewBox: "0 0 21 16" ,class: "header__center__down__user_menu__todo__icon"}
            %path{fill: "currentColor" ,d: "M6.682 12.657L1.67 7.642 0 9.313 6.682 16 21 1.672 19.33 0z"}
          %h1.header__center__down__user_menu__todo__word
            = "やることリスト"
        %li.header__center__down__user_menu__mypage{style: "list-style:none"}
          %h1.header__center__down__user_menu__mypage__word
            - if user_signed_in?
              = link_to user_path(current_user.id) do
                = icon('fa', 'user', class: 'header__mypage-icon')
                マイページ
            - else
              = link_to "新規登録", new_user_registration_path
              = link_to "ログイン", new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title FreemarketSample63b
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = include_gon
    = javascript_include_tag 'application'

  %header
    = render "layouts/header"
  %body
    = yield
    = render "layouts/footer"